version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 20
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-auto-import
    versions:
    - 1.11.2
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.26.2
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.6.2
    - 5.6.4
    - 5.6.5
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-data
    versions:
    - 3.24.0
    - 3.25.0
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: eslint-plugin-ember
    versions:
    - 8.14.0
  commit-message:
    prefix: "[skip netlify]"
